name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # You can also use ubuntu-latest for Linux or macos-latest for macOS

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install leiningen  # Install Leiningen (Clojure build tool) on Windows

    - name: Run tests
      run: lein test   # Run Clojure tests using Leiningen
